### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by johnyradio** [orouits/qjackrcd#12]
### steps to reproduce the behavior
click QJackRcd on menu, 
or enter qjackrcd at command-line

### expected behavior
QJackRcd gui launches

### actual behavior
QJackRcd gui doesn't launch (or launches on ocassionally tries)
```
$ qjackrcd 
cannot read response from jack server (No such file or directory)
attempt to connect to server failed
terminate called after throwing an instance of 'char const*'
Aborted (core dumped)
```

### more info

- Before this issue started, qjackrcd has been running fine for several days (including several restarts and reboots), with no-problem. QJackRcd was visible and functional in qjackctl graph editor. 
- This issue started after i ran qjackrcd for about 10 hours. This was the longest i tried running it without pause. Definitely running for at least 10 hours without pause. 
- But it may have been running for as long as 22 hours. i may have paused qjackrcd (rather than restarted) during the 22 period. 
- When i checked it at 10-hours, it was actively recording (i assume due to my noises at that moment). 
- It would not respond to clicks on the stop-button. Clicking the close-window button closed it. 
- Then it would not restart by menu or command. Restarting the computer didn't fix it. 
- I ran qjackctl, and ensured the server was running. QJackRcd still wouldn't start. 
- On another reboot, QJackRcd gui started from menu, but showed no input. 
- Qjackrcd wasn't visible in qjackctl graph editor. 
- Closed qjackrcd, and reopened from menu a 2nd try. On 2nd try, gui didn't open. 

![shot](https://user-images.githubusercontent.com/6564280/72371069-6f745a00-36b8-11ea-9816-9812142b5b43.jpg)

**Comment by johnyradio** [comment]
i think there's something wrong with my OS or my QJackCtl. 
Today, QJackRcd gui opened, but still no meter deflection on QJackRcd. Got a different error:
```
$ qjackrcd 
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
jackd 0.125.0
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

JACK compiled with System V SHM support.
loading driver ..
apparent rate = 44100
creating alsa driver ... hw:H1|hw:H1|1024|2|44100|0|0|nomon|swmeter|-|32bit
configuring for 44100Hz, period = 1024 frames (23.2 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 16bit little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 16bit little-endian
ALSA: use 2 periods for playback
subgraph starting at QJackRcd timed out (subgraph_wait_fd=9, status = 0, state = Running, pollret = 0 revents = 0x0)
**** alsa_pcm: xrun of at least 5.230 msecs
zombified - calling shutdown handler
```

**Comment by johnyradio** [comment]
Update:
Working now. Changes i made:
In qjackctl > setup > misc > enable D-Bus interface. 

i didn't notice if that was enabled previously, but i never disabled it, so i don't understand what happened. Maybe a system update caused it?

**Comment by be1** [comment]
> i didn't notice if that was enabled previously, but i never disabled it, so i don't understand what happened. Maybe a system update caused it?

Certainly not a system update. Jack startup script and QJackCtl configs are in dot files inside your home directory and system updates _never_ touch to your home directory content.

**Comment by be1** [comment]
@johnyradio can we consider the bug was a false positive and close this ticket ?

**Comment by johnyradio** [comment]
Definitely.
Thx.
