### ISSUE TITLE
fichiers de traduction non-installés avec 1.2.2

### ISSUE THREAD

**Issue by trebmuh** [orouits/qjackrcd#8]
Les fichiers de traduction ne sont plus installés avec la version 1.2.2
Il me semble qu'ils l'étaient avec 1.2.0

**Édition** : concernant la page de manuel, il me manquait docbook-to-man. C'est corrigé.

**Comment by trebmuh** [comment]
Pour ce qui est des traductions, les fichiers .ts ne semblent pas être compilés en .qm lors de la construction.

**Comment by trebmuh** [comment]
J'ai fait un paquet LibraZiK-2 qui lance `lrelease *.ts` au moment de la construction. Ceci crée correctement les fichiers *.qm que je peux ensuite installer correctement dans usr/share/qjackrcd/locale.

Je suppose que quelque chose ne tourne pas rond dans qjackrcd.pro, mais je n'ai pas trouvé quoi.

PS : le paquet pour LZK-2 est actuellement en test, il passera dans le dépôt certainement en fin de semaine

**Comment by orouits** [comment]
Je regarde ça rapidement.
merci !

**Comment by orouits** [comment]
done, just a $$TRANSLATION that is not the right way (do not put $$)

**Comment by orouits** [comment]
I release a 1.2.3 just for this issue.
thank you for your test.

**Comment by trebmuh** [comment]
Nickel. J'ai empaqueté la 1.2.3 et c'est tout bon.
