### ISSUE TITLE
"Cannot connect to server" error

### ISSUE THREAD

**Issue by johnyradio** [orouits/qjackrcd#9]
### expected behavior
Run without error

### actual behavior
```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.14
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2019 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
```

### steps to reproduce the behavior
`$qjackrcd`

**Comment by trebmuh** [comment]
What is the issue there? It looks to me that qjackrcd runs without errors.

**Comment by johnyradio** [comment]
not getting any audio in the interface. 
Trying to use a USB microphone. 
In qjackctl settings, i selected the USB device, and clicked 'Start'.
Then opened qjackrcd. Seems no audio is coming thru. 

When i open qjackrcd from command-line now, i'm not seeing any error messages, but still seems no audio coming.

**Comment by trebmuh** [comment]
qjackrcd, as its name says, is using jack. Hence, you needs to make the audio connection between you're USB mic and qjackrcd's inputs. You can use qjackctl for that as an example.

Jack needs to be launched (with qjackctl as an example), and then, you can click its Connect/Graph buttons to access a canvas where you can make connections.

Just for a better understanding, do you already know how the jack's ecosystem is working or is it the first time for you?

**Comment by johnyradio** [comment]
ok, got it working. First timer. 

it seems selecting capture soundcard in alsa mixer has no effect on routing. Apparently (on my hardware, at least) the USB mic is auto detected and loaded into qjackctl. 

seems i had to draw the connections in graph first time, but auto-connects after that. 

i'll study up. thx!

**Comment by trebmuh** [comment]
yw

**Comment by johnaweiss** [comment]
More info, i still get the 'can't connect to server' message sometimes. 

It seems if jack (or qjackctl?) loses connection to the capture-interface (say if the USB mic is powered off, or the USB hub loses power), then jack server cannot start (or qjackctl can't find jack?). 

The fix that worked for me is to re-assign the input/capture device in QJackCtl > Setup > Settings > Interface, even if it's already correctly assigned. You have switch it to a different interface, then switch it back to correct interface, and Apply. 
https://askubuntu.com/a/935564
